local harpoon = require("harpoon")
harpoon:setup({})

vim.keymap.set("n", "<leader>ma", function()
	harpoon:list():add()
end, { desc = "Harpoon add" })
vim.keymap.set("n", "<leader>a", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Harpoon toggle menu" })

vim.keymap.set("n", "<leader>h", function()
	harpoon:list():select(1)
end, { desc = "Harpoon select 1" })
vim.keymap.set("n", "<leader>j", function()
	harpoon:list():select(2)
end, { desc = "Harpoon select 2" })
vim.keymap.set("n", "<leader>k", function()
	harpoon:list():select(3)
end, { desc = "Harpoon select 3" })
vim.keymap.set("n", "<leader>l", function()
	harpoon:list():select(4)
end, { desc = "Harpoon select 4" })

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<leader>mp", function()
	harpoon:list():prev()
end, { desc = "Harpoon previus" })
vim.keymap.set("n", "<leader>mn", function()
	harpoon:list():next()
end, { desc = "Harpoon next" })
