#+Title: MiniApollo's Gnu Emacs Config
#+Author: MiniApollo
#+Description: My personal emacs configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents :toc:
- [[#core-setup--performance][Core Setup & Performance]]
  - [[#startup-performance][Startup Performance]]
  - [[#auto-tangle-configuration-file][Auto-tangle Configuration file]]
  - [[#show-startup-time][Show startup time]]
  - [[#package-manager][Package manager]]
  - [[#good-defaults][Good Defaults]]
- [[#important-to-load-first][Important to load first]]
  - [[#evil-mode][Evil Mode]]
  - [[#keybinds][Keybinds]]
  - [[#undo][Undo]]
- [[#appearance][Appearance]]
  - [[#set-theme][Set Theme]]
  - [[#transparency][Transparency]]
  - [[#doom-modeline][Doom Modeline]]
  - [[#nerd-icons][Nerd Icons]]
- [[#development][Development]]
  - [[#projectile][Projectile]]
  - [[#consult-dir][Consult-dir]]
  - [[#harpoon][Harpoon]]
  - [[#eglot][Eglot]]
  - [[#masonel][Mason.el]]
  - [[#sideline-flymake][Sideline-flymake]]
  - [[#eldoc-box][Eldoc-box]]
  - [[#yasnippet][Yasnippet]]
  - [[#tree-sitter][Tree-Sitter]]
  - [[#language-modes][Language modes]]
  - [[#terminal][Terminal]]
- [[#version-control][Version Control]]
  - [[#magit][Magit]]
  - [[#diff-hl][Diff-hl]]
- [[#completion][Completion]]
  - [[#corfu][Corfu]]
  - [[#cape][Cape]]
  - [[#orderless][Orderless]]
  - [[#vertico-and-marginalia][Vertico and Marginalia]]
  - [[#embark][Embark]]
  - [[#jinx][Jinx]]
- [[#other-packages][Other packages]]
  - [[#consult][Consult]]
  - [[#sudo-edit][Sudo edit]]
  - [[#evil-mc][Evil-mc]]
  - [[#helpful][Helpful]]
  - [[#diminish][Diminish]]
  - [[#rainbow-delimiters][Rainbow Delimiters]]
  - [[#rainbow-mode][Rainbow Mode]]
  - [[#hl-todo][Hl-todo]]
  - [[#indent-guide][Indent-guide]]
  - [[#which-key][Which-Key]]
  - [[#ws-butler][Ws-butler]]
  - [[#yaml-parser][Yaml parser]]
  - [[#esup][Esup]]
- [[#runtime-performance][Runtime Performance]]

* Core Setup & Performance
These are essential settings and small tweaks that must load before any packages.
They impact the entire configuration, skipping these could result in significantly slower configuration and potential breakage of your setup.

** Startup Performance
Core performace tweaks moved to early-init.el

Enable lexical-binding
#+begin_src emacs-lisp
    ;; -*- lexical-binding: t; -*-
#+end_src

** Auto-tangle Configuration file
Auto-Tangle Org configuration file for better startup times, it refreshes the package-quickstart file.
We'll cover package quickstart in the package manager section later.

If you like to auto tangle an Org file, don't forget to add the following line to the top of your Org document:
(#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the init.el file won't update on change!
To fix this, you need to find this file (C-x C-f), fix the error and press C-c C-v t to tangle it manually.
#+begin_src emacs-lisp
    (defun start/org-babel-tangle-config ()
      "Automatically tangle our init.org config file and refresh package-quickstart when we save it. Credit to Emacs From Scratch for this one!"
      (interactive)
      (when (string-equal (file-name-directory (buffer-file-name))
    					  (expand-file-name user-emacs-directory))
        ;; Dynamic scoping to the rescue
        (let ((org-confirm-babel-evaluate nil))
    	  (org-babel-tangle)
    	  (package-quickstart-refresh)
    	  )
        ))

    (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-config)))
#+end_src

** Show startup time
#+begin_src emacs-lisp
    (defun start/display-startup-time ()
      (interactive)
      (message "Emacs loaded in %s with %d garbage collections."
               (format "%.2f seconds"
                       (float-time
    					(time-subtract after-init-time before-init-time)))
               gcs-done))

    (add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

** Package manager
We use the default built in package manager package.el.
In my experience Package.el is not slow and gets the job done.

To update/upgrade packages, use the package-upgrade-all command.
*** Use-package
A macro that allows you to isolate package configuration in your .emacs file in a way that is both performance-oriented and, well, tidy.
We use it because it makes package configuration really easy.

With Emacs 29 use-package is now built-in.
#+begin_src emacs-lisp
    (require 'use-package-ensure) ;; Load use-package-always-ensure
    (setq use-package-always-ensure t) ;; Always ensures that a package is installed
#+end_src

*** Setting package repositories
Like Linux distributions, Emacs uses repositories to manage its packages.
#+begin_src emacs-lisp
    (setq package-archives '(("melpa" . "https://melpa.org/packages/") ;; Sets default package repositories
                             ("org" . "https://orgmode.org/elpa/")
                             ("elpa" . "https://elpa.gnu.org/packages/")
                             ("nongnu" . "https://elpa.nongnu.org/nongnu/"))) ;; For Eat Terminal
#+end_src

*** Package quickstart
Improves startup times by allowing Emacs to precompute and generate a single, large autoload file.
Instead of re-computing them on every startup.

The larger your configuration, the more it will be felt at startup.

Package quickstart only works with package.el.
If you plan to use a different package manager, remember to remove this section and the package-quickstart-refresh line in the Auto-tangle hook.
#+begin_src emacs-lisp
    (setq package-quickstart t) ;; For blazingly fast startup times, this line makes startup miles faster
#+end_src

*** Package Async
Makes package installation about 15 sec faster.
Also "fixes" multi-vterm not finding vterm (delays vterm module compile).
#+begin_src emacs-lisp
    (use-package async
      :defer
      :custom
      (dired-async-mode t)
      (async-bytecomp-package-mode t)
      (async-bytecomp-allowed-packages '(all))
      (async-package-do-action t))
#+end_src

** Good Defaults
#+begin_src emacs-lisp
    (use-package emacs
      :custom
      ;; Still needed for terminals
      (menu-bar-mode nil)         ;; Disable the menu bar
      (scroll-bar-mode nil)       ;; Disable the scroll bar
      (tool-bar-mode nil)         ;; Disable the tool bar

      (inhibit-startup-screen t)  ;; Disable welcome screen

      (delete-selection-mode t)   ;; Select text and delete it by typing.
      (electric-indent-mode nil)  ;; Turn off the weird indenting that Emacs does by default.
      (electric-pair-mode t)      ;; Turns on automatic parens pairing

      (blink-cursor-mode nil)     ;; Don't blink cursor
      (global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed
      (use-short-answers t)   ;; Since Emacs 29, `yes-or-no-p' will use `y-or-n-p'

      (dired-kill-when-opening-new-dired-buffer t) ;; Dired don't create new buffer
      (recentf-mode t) ;; Enable recent file mode

      (global-visual-line-mode t)           ;; Enable truncated lines
      (display-line-numbers-type 'relative) ;; Relative line numbers
      (global-display-line-numbers-mode t)  ;; Display line numbers

      ;; (pixel-scroll-precision-mode t)     ;; Precise pixel scrolling. i.e. smooth scrolling
      ;; (pixel-scroll-precision-use-momentum nil)

      (native-comp-async-report-warnings-errors 'silent) ;; Don't show native comp errors
      (warning-minimum-level :error) ;; Only show errors in warnings buffer

      (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling
      (scroll-conservatively 10) ;; Smooth scrolling
      (scroll-margin 8)

      (tab-width 4)
      (sgml-basic-offset 4) ;; Set Html mode indentation to 4
      (c-ts-mode-indent-offset 4) ;; Fix weird indentation in c-ts (C, C++)
      (go-ts-mode-indent-offset 4) ;; Fix weird indentation in go-ts

      (make-backup-files nil) ;; Stop creating ~ backup files
      (auto-save-default nil) ;; Stop creating # auto save files
      (delete-by-moving-to-trash t)
      :hook
      (prog-mode . (lambda () (hs-minor-mode t))) ;; Enable folding hide/show globally
      :config
      ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
      (setq custom-file (locate-user-emacs-file "custom-vars.el"))
      (load custom-file 'noerror 'nomessage)
      :bind (
             ([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
             ;; Zooming In/Out
             ("C-+" . text-scale-increase)
             ("C--" . text-scale-decrease)
             ("<C-wheel-up>" . text-scale-increase)
             ("<C-wheel-down>" . text-scale-decrease)
             )
      )
#+end_src

* Important to load first
Packages that we want to load first so we have them as soon as possible if something breaks.
** Evil Mode
An extensible vi/vim layer for Emacs.

Notes:
- You can toggle evil mode with C-z.
- To paste without yank select the text and use P. This line is especially for ThePrimeagen :)
#+begin_src emacs-lisp
    (use-package evil
      :hook (after-init . evil-mode)
      :config
      (evil-set-initial-state 'eat-mode 'insert) ;; Set initial state in eat terminal to insert mode
      (global-set-key [C-backspace] 'evil-delete-backward-word) ;; Make C-backspace less agressive
      :custom
      (evil-want-keybinding nil)    ;; Disable evil bindings in other modes (It's not consistent and not good)
      (evil-want-C-u-scroll t)      ;; Set C-u to scroll up
      (evil-want-C-i-jump nil)      ;; Disables C-i jump
      (org-return-follows-link t)   ;; Sets RETURN key in org-mode to follow links
      (evil-undo-system 'undo-redo) ;; C-r to redo
      (evil-want-fine-undo t)
      ;; Unmap keys in 'evil-maps. If not done, org-return-follows-link will not work
      :bind
      (:map evil-motion-state-map
            ("SPC" . nil)
            ("RET" . nil)
            ("TAB" . nil)))
    (use-package evil-collection
      :after evil
      :config
      ;; Setting where to use evil-collection
      (setq evil-collection-mode-list '(dired ibuffer magit corfu consult info vterm vundo))
      (evil-collection-init))
#+end_src

** Keybinds
My keybindings

Performance:
- Without keybinds: 0.56
- With evil keybinds: 0.56
- With General keybinds: 0.60
#+begin_src emacs-lisp
    (defun mark/open-init-file ()
      "Open init.org configuration file"
      (interactive)
      (find-file "~/.config/emacs/init.org"))

    (defun mark/reload-config()
      "Reload Emacs config"
      (interactive)
      (load-file "~/.config/emacs/init.el"))

    (use-package emacs
      :after (evil)
      :config
      ;; Fix leader key 'SPC'
      (evil-collection-define-key '(normal visual motion) 'dired-mode-map " " 'nil)

      (evil-set-leader '(normal visual motion) (kbd "SPC"))
      (evil-define-key '(normal visual motion) 'global
        (kbd "<leader>.") 'find-file
        (kbd "<leader>,") 'embark-act
        (kbd "<leader>TAB") 'comment-line
        (kbd "<leader>q") 'flymake-show-buffer-diagnostics
        (kbd "<leader>u") 'vundo

        ;; Harpoon
        (kbd "<leader>a") 'harpoon-toggle-quick-menu
        (kbd "<leader>h") 'harpoon-go-to-1
        (kbd "<leader>j") 'harpoon-go-to-2
        (kbd "<leader>k") 'harpoon-go-to-3
        (kbd "<leader>l") 'harpoon-go-to-4

        (kbd "<leader>ma") 'harpoon-add-file
        (kbd "<leader>mf") 'harpoon-toggle-file
        (kbd "<leader>mc") 'harpoon-clear
        (kbd "<leader>mp") 'harpoon-go-to-prev
        (kbd "<leader>mn") 'harpoon-go-to-next

        (kbd "<leader>p") 'projectile-command-map
        (kbd "<leader>sp") 'projectile-discover-projects-in-search-path

        (kbd "<leader>sc") 'mark/open-init-file
        (kbd "<leader>sr") 'consult-recent-file
        (kbd "<leader>sf") 'consult-fd
        (kbd "<leader>sg") 'consult-ripgrep
        (kbd "<leader>sl") 'consult-line
        (kbd "<leader>si") 'consult-imenu
        (kbd "<leader>se") 'sudo-edit
        (kbd "<leader>su") 'sudo-edit-find-file

        (kbd "<leader>so") 'jinx-correct
        (kbd "<leader>sg") 'jinx-languages

        (kbd "<leader>ds") 'consult-buffer
        (kbd "<leader>dk") 'kill-current-buffer
        (kbd "<leader>di") 'ibuffer
        (kbd "<leader>dn") 'next-buffer
        (kbd "<leader>dp") 'previous-buffer
        (kbd "<leader>dr") 'revert-buffer
        (kbd "<leader>dv") 'dired
        (kbd "<leader>dj") 'dired-jump
        (kbd "<leader>da") 'consult-dir

        (kbd "<leader>ee") 'eglot-reconnect
        (kbd "<leader>ed") 'eldoc-doc-buffer
        (kbd "<leader>ef") 'eglot-format
        (kbd "<leader>el") 'consult-flymake
        (kbd "<leader>en") 'flymake-goto-next-error
        (kbd "<leader>ep") 'flymake-goto-prev-error

        (kbd "<leader>ea") 'eglot-code-actions
        (kbd "<leader>er") 'eglot-rename
        (kbd "<leader>ei") 'xref-find-definitions
        (kbd "<leader>es") 'xref-find-references

        (kbd "<leader>evb") 'eval-buffer
        (kbd "<leader>evr") 'eval-region

        (kbd "<leader>gs") 'magit-status

        (kbd "<leader>rq") 'save-buffers-kill-emacs
        (kbd "<leader>rr") 'mark/reload-config

        (kbd "<leader>vm") 'multi-vterm
        (kbd "<leader>vn") 'multi-vterm-next
        (kbd "<leader>vp") 'multi-vterm-prev
        (kbd "<leader>vd") 'multi-vterm-dedicated-toggle

        (kbd "<leader>tt") 'visual-line-mode
        (kbd "<leader>tl") 'display-line-numbers-mode
        (kbd "<leader>tm") 'evil-mc-mode
        ))
#+end_src

** Undo
Vundo: Visualizes undo history.
Undo-fu-session: Persistent undo history
#+begin_src emacs-lisp
    (use-package undo-fu-session
      :hook (after-init . undo-fu-session-global-mode)
      :custom (undo-fu-session-incompatible-files '("\\.gpg$" "/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
      :config
      ;; Increase undo history limits to reduce likelihood of data loss
      (setq undo-limit 256000           ;; 256kb (default is 160kb)
            undo-strong-limit (* 1024 1024 2)   ;; 2mb   (default is 240kb)
            undo-outer-limit (* 1024 1024 36))  ;; 36mb  (default is 24mb)
      )

    (use-package vundo
      :defer
      :custom
      (vundo-glyph-alist vundo-unicode-symbols))
#+end_src

* Appearance
** Set Theme
Set gruvbox theme, if you want some themes try out doom-themes.
Use consult-theme to easily try out themes (*Epilepsy* Warning).
#+begin_src emacs-lisp
    (use-package gruvbox-theme
      :config
      (setq gruvbox-bold-constructs t)
      (load-theme 'gruvbox-dark-medium t)) ;; We need to add t to trust this package
#+end_src

** Transparency
With Emacs version 29, true transparency has been added.
#+begin_src emacs-lisp
    (add-to-list 'default-frame-alist '(alpha-background . 90)) ;; For all new frames henceforth

    ;; Transparency in terminal
    (defun start/on-after-init ()
      (unless (display-graphic-p (selected-frame))
        (set-face-background 'default "unspecified-bg" (selected-frame))))

    (add-hook 'window-setup-hook 'start/on-after-init)
#+end_src

** Doom Modeline
A fancy, fast and customizable mode-line.
#+begin_src emacs-lisp
    (use-package doom-modeline
      :custom
      (doom-modeline-height 25) ;; Set modeline height
      :hook (after-init . doom-modeline-mode))
#+end_src

** Nerd Icons
This is an icon set that can be used with dired, ibuffer and other Emacs packages.
Don't forget nerd-icons-install-fonts to install the resource fonts.

We use nerd-icons because it supports both GUI and TUI unlike all-the-icons.
Also Doom modeline requires nerd icons.
#+begin_src emacs-lisp
    (use-package nerd-icons
      :if (display-graphic-p))

    (use-package nerd-icons-dired
      :hook (dired-mode . (lambda () (nerd-icons-dired-mode t))))

    (use-package nerd-icons-ibuffer
      :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

* Development
** Projectile
Project interaction library for Emacs.

Emacs has a built in project manager called project.el, but we don't use it.
You can try it out with the keybinds under C-x p because project.el does not require any special setup to use.

We use projectile because it:
- supports more features and project types.
- has better integration with projects.
- has better documentation.
- is developed faster.
More [[https://docs.projectile.mx/projectile/projectile_vs_project.html][reasons]] to use projectile.
#+begin_src emacs-lisp
    (use-package projectile
      :hook (after-init . projectile-mode)
      :custom
      (projectile-auto-discover nil) ;; Disable auto search for better startup times ;; Search with a keybind
      (projectile-run-use-comint-mode t) ;; Interactive run dialog when running projects inside emacs (like giving input)
      (projectile-switch-project-action #'projectile-dired) ;; Open dired when switching to a project
      (projectile-project-search-path '(("/mnt/Ext4D/Mark/Projektek/" . 2)
                                        ("/mnt/Ext4D/Mark/Projektek/Desktop/Gyakorlas/" . 2)
                                        ("/mnt/Ext4D/Mark/Projektek/Desktop/Iskola/" . 3)
    									)))
#+end_src

** Consult-dir
#+begin_src emacs-lisp
    (use-package consult-dir
      :defer
      :custom
      (consult-dir-default-command #'consult-dir-dired)
      :config
      ;; A function that returns a list of directories
      (defun consult-dir--work-dirs ()
        "Return list of work dirs."
        (append
         (split-string (shell-command-to-string "find ~/.config -maxdepth 1 -type d") "\n" t)
         (split-string (shell-command-to-string "find /mnt/Ext4D/Mark/Projektek/ /mnt/Ext4D/Mark/Projektek/Desktop/Gyakorlas/ /mnt/Ext4D/Mark/Projektek/Desktop/Iskola/ -mindepth 2 -maxdepth 2 -type d") "\n" t)
         ))

      ;; A consult source that calls this function
      (defvar consult-dir--source-work
        `(:name     "Work Directories"
                    :narrow   ?w
                    :category file
                    :face     consult-file
                    :history  file-name-history
                    :enabled  ,(lambda () (executable-find "find"))
                    :items    ,#'consult-dir--work-dirs)
        "Work directory source for `consult-dir'.")

      ;; Adding to the list of consult-dir sources
      (add-to-list 'consult-dir-sources 'consult-dir--source-work t))
#+end_src

** Harpoon
#+begin_src emacs-lisp
    (use-package harpoon :defer)
#+end_src

** Eglot
Built in Emacs client for the Language Server Protocol.
We use Eglot because it is fast and minimal.
For more: C-h i: g: (eglot)Top

Eglot does not automatically download LSP servers. It requires separate download.
The easiest way to install LSP servers is with a package manager.

If you can't use a package manager you can do the following:
- Download the server (e.g. from github)
- Add the binary/executable to your path.
- Or customize the eglot-server-programs list.
To control how a LSP server is started customize the eglot-server-programs list.
#+begin_src emacs-lisp
    (use-package eglot
      :ensure nil ;; Don't install eglot because it's now built-in
      :hook ((c-ts-mode c++-ts-mode
                        csharp-mode java-ts-mode
                        html-ts-mode css-ts-mode
                        js-ts-mode typescript-ts-mode
                        php-ts-mode cmake-ts-mode
                        go-ts-mode rust-ts-mode
                        haskell-mode bash-ts-mode
                        gdscript-mode glsl-mode
                        hyprlang-ts-mode haskell-mode)
             . eglot-ensure)
      :custom
      ;; Good default
      (eglot-events-buffer-size 0) ;; No event buffers (LSP server logs)
      (eglot-autoshutdown t);; Shutdown unused servers.
      (eglot-report-progress nil) ;; Disable LSP server logs (Don't show lsp messages at the bottom, java)
      ;; Manual lsp servers
      :config
      (add-to-list 'eglot-server-programs
                   `(hyprlang-ts-mode . ("hyprls" "-lsp")))
      )
#+end_src

** Mason.el
Package manager for LSP, DAP, linters, and more for the Emacs Operating System.
I waited so long for a package like this.
#+begin_src emacs-lisp
    (use-package mason
      :hook (after-init . mason-ensure))
#+end_src

** Sideline-flymake
Show flymake errors with sideline
#+begin_src emacs-lisp
    (use-package sideline-flymake
      :hook (flymake-mode . sideline-mode)
      :custom
      (sideline-flymake-display-mode 'line) ;; show errors on the current line
      (sideline-backends-right '(sideline-flymake)))
#+end_src

** Eldoc-box
Display eldoc documentation in a popup box
#+begin_src emacs-lisp
    (use-package eldoc-box
      :hook (prog-mode . eldoc-box-hover-at-point-mode))
#+end_src

** Yasnippet
A template system for Emacs. And yasnippet-snippets is a snippet collection package.
To use it write out the full keyword (or use autocompletion) and press Tab.
#+begin_src emacs-lisp
    (use-package yasnippet-snippets
      :hook (prog-mode . yas-minor-mode))

    (defun mark/corfu-yas-tab-handler ()
      "Prioritize corfu over yasnippet when yasnippet is active"
      (interactive)
      ;; There is no direct way to get if corfu is currently displayed so we watch the completion index
      (if (> corfu--index -1)
          (corfu-complete)
        (yas-next-field-or-maybe-expand)
        )
      )
    (use-package emacs
      :after (yasnippet corfu)
      :bind
      (:map yas-keymap
            ("TAB" . mark/corfu-yas-tab-handler))
      )
#+end_src

** Tree-Sitter
A parser generator tool and an incremental parsing library.
Check out TJ's [[https://www.youtube.com/watch?v=09-9LltqWLY][video]] to learn why you should use it.

With Emacs 29 Tree-Sitter is now built-in. You may need to compile Emacs from source to have it enabled.
You also need to have a compiler installed so Emacs can compile the parsers into a shared library.
For more info about how to use Tree-Sitter check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][masteringemacs]] article.

Using Tree-Sitter is somewhat hacky because it requires you to:
- manually manage a source list of the parsers you want to use.
- remap the major modes you want to use.
You can also use treesit-auto, but it is updated quite slowly so we don't use it.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp
    (setq treesit-language-source-alist
          '((bash "https://github.com/tree-sitter/tree-sitter-bash")
            (cmake "https://github.com/uyha/tree-sitter-cmake")
            (c "https://github.com/tree-sitter/tree-sitter-c")
            (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
            (css "https://github.com/tree-sitter/tree-sitter-css")
            (elisp "https://github.com/Wilfred/tree-sitter-elisp")
            (go "https://github.com/tree-sitter/tree-sitter-go")
            (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
            (html "https://github.com/tree-sitter/tree-sitter-html")
            (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
            (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
            (json "https://github.com/tree-sitter/tree-sitter-json")
            (make "https://github.com/alemuller/tree-sitter-make")
            (markdown "https://github.com/ikatyang/tree-sitter-markdown")
            (python "https://github.com/tree-sitter/tree-sitter-python")
            (rust "https://github.com/tree-sitter/tree-sitter-rust")
            (toml "https://github.com/tree-sitter/tree-sitter-toml")
            (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
            (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
            (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

    (defun start/install-treesit-grammars ()
      "Install missing treesitter grammars"
      (interactive)
      (dolist (grammar treesit-language-source-alist)
        (let ((lang (car grammar)))
          (unless (treesit-language-available-p lang)
            (treesit-install-language-grammar lang)))))

    ;; Call this function to install missing grammars
    (add-hook 'after-init-hook #'start/install-treesit-grammars)

    ;; Optionally, add any additional mode remappings not covered by defaults
    (setq major-mode-remap-alist
          '((yaml-mode . yaml-ts-mode)
            (sh-mode . bash-ts-mode)
            (c-mode . c-ts-mode)
            (c++-mode . c++-ts-mode)
            (css-mode . css-ts-mode)
            (python-mode . python-ts-mode)
            (mhtml-mode . html-ts-mode)
            (javascript-mode . js-ts-mode)
            (json-mode . json-ts-mode)
            (typescript-mode . typescript-ts-mode)
            (conf-toml-mode . toml-ts-mode)
            ))
    (setq treesit-font-lock-level 3)

    ;; Or if there is no built in mode
    (use-package cmake-ts-mode :ensure nil :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))
    (use-package go-mod-ts-mode :ensure nil :mode "\\.mod\\'")
    (use-package lua-ts-mode :ensure nil :mode "\\.lua\\'")
    (use-package rust-ts-mode :ensure nil :mode "\\.rs\\'")
    (use-package tsx-ts-mode :ensure nil :mode "\\.tsx\\'")
    (use-package yaml-ts-mode :ensure nil :mode ("\\.yaml\\'" "\\.yml\\'"))

    (use-package hyprlang-ts-mode
      :mode ("/hypr/.*\\.conf\\'")
      :custom
      (hyprlang-ts-mode-indent-offset 4))
#+end_src

*** Fix go-ts-mode highlighting
#+begin_src emacs-lisp
    ;; https://www.reddit.com/r/emacs/comments/1c5dkup/how_to_modify_syntax_highlighting_in_treesitter/
    ;; https://github.com/emacs-mirror/emacs/blob/master/admin/notes/tree-sitter/starter-guide
    (use-package go-ts-mode
      :ensure nil
      :mode "\\.go\\'"
      :config
      (defvar mark/ts-font-lock-settings
        (treesit-font-lock-rules
         :language 'go ;; What language
         :feature 'function-highlight ;; A unique feature name that we can toggle.

         `(
           ;; Function calls
           (call_expression
            function: (selector_expression
                       field: (field_identifier) @font-lock-function-call-face)) ;; Use 'describe-face' to find faces
           ;; Property values
           (argument_list
            (selector_expression
             field: (field_identifier) @font-lock-property-use-face))
           (expression_list
            (selector_expression
             field: (field_identifier) @font-lock-property-use-face))
           ;; ((Treesit patern) @defface_Settings)
           ))
        "Go-ts-mode settings, fix not highlighting function calls and property values")

      (add-hook 'go-ts-mode-hook
                (lambda () (setq-local treesit-font-lock-settings
                                       (append treesit-font-lock-settings
                                               mark/ts-font-lock-settings))))
      )
#+end_src

** Language modes
Emacs contains many “editing modes” that alter its basic behavior in
useful ways. These are divided into “major modes” and “minor modes”.
For more: C-h i: g: (emacs)Modes

Some programming languages require the installation of specific modes to fully integrate and function within Emacs.
These packages are often necessary for features like syntax highlighting, code formatting, linting, and language-specific features.

*** Markdown mode
#+begin_src emacs-lisp
    (use-package markdown-mode
      :mode "\\.md\\'")
#+end_src

*** Haskell mode
#+begin_src emacs-lisp
    (use-package haskell-mode
      :mode "\\.hs\\'")
#+end_src

*** Org Mode
One of the things that Emacs is loved for.
Once you've used it for a bit, you'll understand why people love it. Even reading about it can be inspiring!
For example, this document is effectively the source code and descriptions bound into the one document,
much like the literate programming ideas that Donald Knuth made famous.

We use an Org mode document for our Emacs configuration because it provides:
- Better organization: It lets us structure with outlines, headings, and tags.
- Literate Documentation: It's a document, not just source code.
- Fast Navigation: Quickly jump to sections with something like Imenu.
#+begin_src emacs-lisp
    (use-package org
      :ensure nil
      :custom
      (org-edit-src-content-indentation 4) ;; Set src block automatic indent to 4 instead of 2.

      :hook
      (org-mode . org-indent-mode) ;; Indent text
      ;; The following prevents <> from auto-pairing when electric-pair-mode is on.
      ;; Otherwise, org-tempo is broken when you try to <s TAB...
      (org-mode . (lambda ()
                    (setq-local electric-pair-inhibit-predicate
                                `(lambda (c)
                                   (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
      )
#+end_src

**** Table of Contents
#+begin_src emacs-lisp
    (use-package toc-org
      :commands toc-org-enable
      :hook (org-mode . toc-org-mode))
#+end_src

**** Org Superstar
Prettify headings and plain lists in Org mode. Modern version of org-bullets.
#+begin_src emacs-lisp
    (use-package org-superstar
      :after org
      :hook (org-mode . org-superstar-mode))
#+end_src

**** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.
Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.
#+begin_src emacs-lisp
    (use-package org-tempo
      :ensure nil
      :after org)
#+end_src

** Terminal
*** VTerm
Fully-fledged terminal emulator inside GNU Emacs.
Fast, POSIX compliant shell, handles UIs well.
#+begin_src emacs-lisp
    (use-package vterm
      :defer
      :custom
      (vterm-max-scrollback 5000)
      (vterm-always-compile-module t))
#+end_src
*** Multi-vterm
Managing multiple vterm buffers in Emacs
#+begin_src emacs-lisp
    (use-package multi-vterm
      :after vterm)
#+end_src

*** Exec-path-from-shell
#+begin_src emacs-lisp
    (use-package exec-path-from-shell
      :hook (after-init . exec-path-from-shell-initialize))
#+end_src

* Version Control
** Magit
Complete text-based user interface to Git.
#+begin_src emacs-lisp
    (use-package transient :defer)
    (use-package magit
      :defer
      :custom (magit-diff-refine-hunk (quote all)) ;; Shows inline diff
      :config
      (define-key transient-map (kbd "<escape>") 'transient-quit-one) ;; Make escape quit magit prompts
      (setopt magit-format-file-function #'magit-format-file-nerd-icons) ;; Magit nerd icons
      ;; Fix evil mode 'SPC' leader key
      :bind (:map magit-mode-map
                  ("SPC" . nil)
                  :map magit-diff-mode-map
                  ("SPC" . nil))
      )
#+end_src

** Diff-hl
Highlights uncommitted changes on the left side of the window (area also known as the "gutter"), allows you to jump between and revert them selectively.
#+begin_src emacs-lisp
    (use-package diff-hl
      :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
             (magit-post-refresh . diff-hl-magit-post-refresh)
             (after-init . global-diff-hl-mode)))
#+end_src

* Completion
** Corfu
Enhances in-buffer completion with a small completion popup.
Corfu is a small package, which relies on the Emacs completion facilities and concentrates on providing a polished completion.
For more configuration options check out their [[https://github.com/minad/corfu][git repository]].
Notes:
- To enter Orderless field separator, use M-SPC.
#+begin_src emacs-lisp
    (use-package corfu
      ;; Optional customizations
      :custom
      (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
      (corfu-auto t)                 ;; Enable auto completion
      (corfu-auto-prefix 2)          ;; Minimum length of prefix for auto completion.
      (corfu-popupinfo-mode t)       ;; Enable popup information
      (corfu-popupinfo-delay 0.5)    ;; Lower popup info delay to 0.5 seconds from 2 seconds
      (corfu-separator ?\s)          ;; Orderless field separator, Use M-SPC to enter separator

      (completion-ignore-case t)
      ;; Emacs 30 and newer: Disable Ispell completion function.
      ;; Try `cape-dict' as an alternative.
      (text-mode-ispell-word-completion nil)

      ;; Enable indentation+completion using the TAB key.
      ;; `completion-at-point' is often bound to M-TAB.
      (tab-always-indent 'complete)

      (corfu-preview-current nil) ;; Don't insert completion without confirmation
      ;; Recommended: Enable Corfu globally.  This is recommended since Dabbrev can
      ;; be used globally (M-/).  See also the customization variable
      ;; `global-corfu-modes' to exclude certain modes.
      :hook (after-init . global-corfu-mode)
      )

    (use-package nerd-icons-corfu
      :after corfu
      :init (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

** Cape
Provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI.
Notes:
- The functions that are added later will be the first in the completion list.
- Be aware when adding Capfs (Completion-at-point-functions) to the list since each of the Capfs adds a small runtime cost.
Read the [[https://github.com/minad/cape#configuration][configuration section]] in Cape's readme for more information.
#+begin_src emacs-lisp
    (use-package yasnippet-capf
      :after (cape yasnippet)
      :config
      (add-to-list 'completion-at-point-functions #'yasnippet-capf))

    (defun mark/eglot-capf ()
      (setq-local completion-at-point-functions
                  (list (cape-capf-super
                         #'eglot-completion-at-point
                         #'yasnippet-capf))))

    (use-package cape
      :after corfu
      :init
      ;; Add to the global default value of `completion-at-point-functions' which is
      ;; used by `completion-at-point'.  The order of the functions matters, the
      ;; first function returning a result wins.  Note that the list of buffer-local
      ;; completion functions takes precedence over the global list.

      ;; The functions that are added later will be the first in the list
      (add-hook 'completion-at-point-functions #'cape-dabbrev) ;; Complete word from current buffers
      (add-hook 'completion-at-point-functions #'cape-dict) ;; Dictionary completion
      (add-hook 'completion-at-point-functions #'cape-file) ;; Path completion
      (add-hook 'completion-at-point-functions #'cape-elisp-block) ;; Complete elisp in Org or Markdown mode
      (add-hook 'completion-at-point-functions #'cape-keyword) ;; Keyword completion
      (add-hook 'eglot-managed-mode-hook #'mark/eglot-capf)

      ;;(add-hook 'completion-at-point-functions #'cape-abbrev) ;; Complete abbreviation
      ;;(add-hook 'completion-at-point-functions #'cape-history) ;; Complete from Eshell, Comint or minibuffer history
      ;;(add-hook 'completion-at-point-functions #'cape-line) ;; Complete entire line from current buffer
      ;;(add-hook 'completion-at-point-functions #'cape-elisp-symbol) ;; Complete Elisp symbol
      ;;(add-hook 'completion-at-point-functions #'cape-tex) ;; Complete Unicode char from TeX command, e.g. \hbar
      ;;(add-hook 'completion-at-point-functions #'cape-sgml) ;; Complete Unicode char from SGML entity, e.g., &alpha
      ;;(add-hook 'completion-at-point-functions #'cape-rfc1345) ;; Complete Unicode char using RFC 1345 mnemonics
      )
#+end_src

** Orderless
Completion style that divides the pattern into space-separated components and matches candidates that match all of the components in any order.
Recommended for packages like vertico, corfu.
#+begin_src emacs-lisp
    (use-package orderless
      :defer
      :custom
      (completion-styles '(orderless basic))
      (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** Vertico and Marginalia
- Vertico: Provides a performant and minimalistic vertical completion UI based on the default completion system.
- Savehist: Saves completion history.
- Marginalia: Adds extra metadata for completions in the margins (like descriptions).
- Nerd-icons-completion: Adds icons to completion candidates using the built in completion metadata functions.

We use these packages because they use Emacs native functions. Unlike Ivy or Helm.
#+begin_src emacs-lisp
    (use-package vertico
      :hook (after-init . vertico-mode)
      :bind (:map vertico-map
          		  ("C-j" . vertico-next)
          		  ("C-k" . vertico-previous)
          		  ("C-u" . vertico-scroll-down)
          		  ("C-d" . vertico-scroll-up))
      :custom
      (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
      )

    (savehist-mode) ;; Enables save history mode

    (use-package marginalia
      :after vertico
      :config
      (marginalia-mode))

    (use-package nerd-icons-completion
      :after marginalia
      :config
      (nerd-icons-completion-mode)
      :hook
      (marginalia-mode . nerd-icons-completion-marginalia-setup))
#+end_src

** Embark
Emacs Mini-Buffer Actions Rooted in Keymaps
#+begin_src emacs-lisp
    (use-package embark :defer)
    (use-package embark-consult
      :hook
      (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Jinx
Enchanted Spell Checker
#+begin_src emacs-lisp
    (use-package jinx
      :hook (after-init . global-jinx-mode))
#+end_src

* Other packages
All the package setups that don't need much tweaking.
** Consult
Provides search and navigation commands based on the Emacs completion function.
Check out their [[https://github.com/minad/consult][git repository]] for more awesome functions.
#+begin_src emacs-lisp
    (use-package consult
      ;; Enable automatic preview at point in the *Completions* buffer. This is
      ;; relevant when you use the default completion UI.
      :hook (completion-list-mode . consult-preview-at-point-mode)
      :init
      ;; Optionally configure the register formatting. This improves the register
      ;; preview for `consult-register', `consult-register-load',
      ;; `consult-register-store' and the Emacs built-ins.
      (setq register-preview-delay 0.5
            register-preview-function #'consult-register-format)

      ;; Optionally tweak the register preview window.
      ;; This adds thin lines, sorting and hides the mode line of the window.
      (advice-add #'register-preview :override #'consult-register-window)

      ;; Use Consult to select xref locations with preview
      (setq xref-show-xrefs-function #'consult-xref
            xref-show-definitions-function #'consult-xref)
      :config
       ;;;; 4. projectile.el (projectile-project-root)
      (autoload 'projectile-project-root "projectile")
      (setq consult-project-function (lambda (_) (projectile-project-root)))
      )
#+end_src

** Sudo edit
Utilities for opening files with root privileges (also works with doas).
#+begin_src emacs-lisp
    (use-package sudo-edit
      :defer
      :custom (sudo-edit-local-method "doas")) ;; To use doas
#+end_src

** Evil-mc
Multiple-cursors for evil mode.
#+begin_src emacs-lisp
    (use-package evil-mc
      :defer)
#+end_src

** Helpful
An alternative to the built-in Emacs help that provides much more contextual information.
#+begin_src emacs-lisp
    (use-package helpful
      :bind
      ;; Note that the built-in `describe-function' includes both functions
      ;; and macros. `helpful-function' is functions only, so we provide
      ;; `helpful-callable' as a drop-in replacement.
      ("C-h f" . helpful-callable)
      ("C-h v" . helpful-variable)
      ("C-h k" . helpful-key)
      ("C-h x" . helpful-command)
      )
#+end_src

** Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.
With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
    (use-package diminish :defer)
#+end_src

** Rainbow Delimiters
Adds colors to brackets.
#+begin_src emacs-lisp
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Rainbow Mode
Display the actual color as a background for any hex color value (ex. #ffffff).
#+begin_src emacs-lisp
    (use-package rainbow-mode
      :diminish
      :hook
      ((org-mode prog-mode) . rainbow-mode))
#+end_src

** Hl-todo
Highlight TODO keywords
#+begin_src emacs-lisp
    (use-package hl-todo
      :hook
      ((prog-mode yaml-ts-mode) . hl-todo-mode)
      :config
      ;; From doom emacs
      (setq hl-todo-highlight-punctuation ":"
            hl-todo-keyword-faces
            '(;; For reminders to change or add something at a later date.
              ("TODO" warning bold)
              ;; For code (or code paths) that are broken, unimplemented, or slow,
              ;; and may become bigger problems later.
              ("FIXME" error bold)
              ;; For code that needs to be revisited later, either to upstream it,
              ;; improve it, or address non-critical issues.
              ("REVIEW" font-lock-keyword-face bold)
              ;; For code smells where questionable practices are used
              ;; intentionally, and/or is likely to break in a future update.
              ("HACK" font-lock-constant-face bold)
              ;; For sections of code that just gotta go, and will be gone soon.
              ;; Specifically, this means the code is deprecated, not necessarily
              ;; the feature it enables.
              ("DEPRECATED" font-lock-doc-face bold)
              ;; Extra keywords commonly found in the wild, whose meaning may vary
              ;; from project to project.
              ("NOTE" success bold)
              ("BUG" error bold)
              ("XXX" font-lock-constant-face bold)))
      )
#+end_src

** Indent-guide
Show indendation
#+begin_src emacs-lisp
    (use-package indent-guide
      :hook
      (prog-mode . indent-guide-mode)
      :config
      (setq indent-guide-char "│")) ;; Set the character used for the indent guide.
#+end_src

** Which-Key
Which-key is a helper utility for keychords (which key to press).
#+begin_src emacs-lisp
    (use-package which-key
      :ensure nil ;; Don't install which-key because it's now built-in
      :hook (after-init . which-key-mode)
      :diminish
      :custom
      (which-key-side-window-location 'bottom)
      (which-key-sort-order #'which-key-key-order-alpha) ;; Same as default, except single characters are sorted alphabetically
      (which-key-sort-uppercase-first nil)
      (which-key-add-column-padding 1) ;; Number of spaces to add to the left of each column
      (which-key-min-display-lines 6)  ;; Increase the minimum lines to display because the default is only 1
      (which-key-idle-delay 0.8)       ;; Set the time delay (in seconds) for the which-key popup to appear
      (which-key-max-description-length 25)
      (which-key-allow-imprecise-window-fit nil)) ;; Fixes which-key window slipping out in Emacs Daemon
#+end_src

** Ws-butler
Removes whitespace from the ends of lines.
#+begin_src emacs-lisp
    (use-package ws-butler
      :hook (after-init . ws-butler-global-mode))
#+end_src

** Yaml parser
For development
#+begin_src emacs-lisp
    (use-package yaml :defer)
#+end_src

** Esup
Emacs Start Up Profiler
#+begin_src emacs-lisp
    (use-package esup
      :defer
      :custom
      (esup-depth 0))
#+end_src

* Runtime Performance
Dial the GC threshold back down so that garbage collection happens more frequently but in less time.
#+begin_src emacs-lisp
    ;; Make gc pauses faster by decreasing the threshold.
    (setq gc-cons-threshold (* 1024 1024 2) ;; 2mb
          gc-cons-percentage 0.2)
#+end_src
